export const contactList = [
  {
    id: 1,
    name: 'Rohan Singh',
    ProfilePic: '/Profile/pp1.png',
    lastText: "Hey, what's up?",
    lastTextTime: '10:15 AM',
  },
  {
    id: 2,
    name: 'Sneha Patel',
    ProfilePic: '/Profile/pp2.png',
    lastText: "I'll call you later.",
    lastTextTime: '09:30 AM',
  },
  {
    id: 3,
    name: 'Aarav Mehta',
    ProfilePic: '/Profile/pp3.png',
    lastText: 'Can you send me the file?',
    lastTextTime: '02:45 PM',
  },
  {
    id: 4,
    name: 'Ishita Gupta',
    ProfilePic: '/Profile/pp4.png',
    lastText: 'Thanks for the update!',
    lastTextTime: '11:00 AM',
  },
  {
    id: 5,
    name: 'Karan Sharma',
    ProfilePic: '/Profile/pp5.png',
    lastText: 'See you tomorrow!',
    lastTextTime: '04:00 PM',
  },
  {
    id: 6,
    name: 'Priya Joshi',
    ProfilePic: '/Profile/pp6.png',
    lastText: 'Meeting postponed to Friday.',
    lastTextTime: '08:20 AM',
  },
  {
    id: 7,
    name: 'Amit Desai',
    ProfilePic: '/Profile/pp7.png',
    lastText: 'Got it, thanks!',
    lastTextTime: '01:10 PM',
  },
  {
    id: 8,
    name: 'Meera Kapoor',
    ProfilePic: '/Profile/pp8.png',
    lastText: 'Happy Birthday!',
    lastTextTime: '12:00 PM',
  },
  {
    id: 9,
    name: 'Rajesh Nair',
    ProfilePic: '/Profile/pp9.png',
    lastText: "Let's catch up this weekend.",
    lastTextTime: '06:15 PM',
  },
  {
    id: 10,
    name: 'Ananya Verma',
    ProfilePic: '/Profile/pp10.png',
    lastText: 'Can you share the location?',
    lastTextTime: '03:30 PM',
  },
  {
    id: 11,
    name: 'Vikas Malhotra',
    ProfilePic: '/Profile/pp11.png',
    lastText: 'Let me check and get back.',
    lastTextTime: '05:45 PM',
  },
  {
    id: 12,
    name: 'Riya Agarwal',
    ProfilePic: '/Profile/pp12.png',
    lastText: 'Congrats on the promotion!',
    lastTextTime: '07:50 PM',
  },
  {
    id: 13,
    name: 'Siddharth Jain',
    ProfilePic: '/Profile/pp13.png',
    lastText: "I'll send it right away.",
    lastTextTime: '09:10 AM',
  },
  {
    id: 14,
    name: 'Niharika Das',
    ProfilePic: '/Profile/pp14.png',
    lastText: 'Where are we meeting?',
    lastTextTime: '10:40 AM',
  },
  {
    id: 15,
    name: 'Arjun Kulkarni',
    ProfilePic: '/Profile/pp15.png',
    lastText: 'Can we reschedule?',
    lastTextTime: '11:30 AM',
  },
  {
    id: 16,
    name: 'Pooja Reddy',
    ProfilePic: '/Profile/pp16.png',
    lastText: 'Got your message.',
    lastTextTime: '01:20 PM',
  },
  {
    id: 17,
    name: 'Rahul Khanna',
    ProfilePic: '/Profile/pp17.png',
    lastText: 'Let me know your availability.',
    lastTextTime: '02:35 PM',
  },
  {
    id: 18,
    name: 'Tanya Chauhan',
    ProfilePic: '/Profile/pp18.png',
    lastText: 'Thank you so much!',
    lastTextTime: '05:10 PM',
  },
  {
    id: 19,
    name: 'Kabir Bansal',
    ProfilePic: '/Profile/pp19.png',
    lastText: 'Looking forward to it.',
    lastTextTime: '06:25 PM',
  },
  {
    id: 20,
    name: 'Aditi Sehgal',
    ProfilePic: '/Profile/pp20.png',
    lastText: 'See you soon!',
    lastTextTime: '08:15 PM',
  },
]

export const messageList = [
  {
    id: 1,
    messageType: 'Text',
    text: 'Hi',
    senderID: 0,
    addedOn: '12:00 PM',
  },
  {
    id: 2,
    messageType: 'Text',
    text: 'Hello',
    senderID: 1,
    addedOn: '12:02 PM',
  },
  {
    id: 3,
    messageType: 'Text',
    text: 'How are you?',
    senderID: 0,
    addedOn: '12:03 PM',
  },
  {
    id: 4,
    messageType: 'Text',
    text: 'I am fine. What about you?',
    senderID: 1,
    addedOn: '12:05 PM',
  },
  {
    id: 5,
    messageType: 'Text',
    text: 'I am good, thanks!',
    senderID: 0,
    addedOn: '12:07 PM',
  },
  {
    id: 6,
    messageType: 'Text',
    text: 'What are you doing today?',
    senderID: 1,
    addedOn: '12:10 PM',
  },
  {
    id: 7,
    messageType: 'Text',
    text: 'Just working on a project. You?',
    senderID: 0,
    addedOn: '12:12 PM',
  },
  {
    id: 8,
    messageType: 'Text',
    text: 'Same here. Busy day!',
    senderID: 1,
    addedOn: '12:14 PM',
  },
  {
    id: 9,
    messageType: 'Text',
    text: 'Take care and stay hydrated!',
    senderID: 0,
    addedOn: '12:16 PM',
  },
  {
    id: 10,
    messageType: 'Text',
    text: 'You too. Catch up later!',
    senderID: 1,
    addedOn: '12:18 PM',
  },
  {
    id: 11,
    messageType: 'Text',
    text: 'Sure. Bye!',
    senderID: 0,
    addedOn: '12:20 PM',
  },
  {
    id: 12,
    messageType: 'Image',
    text: 'Sent an image',
    senderID: 1,
    addedOn: '12:22 PM',
  },
  {
    id: 13,
    messageType: 'Text',
    text: 'Nice picture!',
    senderID: 0,
    addedOn: '12:24 PM',
  },
  {
    id: 14,
    messageType: 'Text',
    text: 'Thanks!',
    senderID: 1,
    addedOn: '12:26 PM',
  },
]
